FROM amazonlinux:2

WORKDIR /app

COPY backend/venv /app/venv

COPY backend/requierments.txt /app

RUN yum install -y python3
RUN /app/venv/bin/python -m pip install --no-cache-dir -r requirements.txt

COPY backend/ /app

EXPOSE 5000

ENV NAME World

CMD ["/app/venv/bin/python", "app.py"]